plugins {
    id 'com.android.library'
}

def pojavRoot = file('../engine/pojav')
def pojavApp = file('../engine/pojav/app_pojavlauncher')

android {
    namespace 'net.kdt.pojavlaunch'
    compileSdk 35

    defaultConfig {
        minSdk 26
        targetSdk 34
        multiDexEnabled true

        resValue 'string', 'application_package', 'git.neko.cryonix'
        resValue 'string', 'storageProviderAuthorities', 'git.neko.cryonix.scoped.gamefolder'
        resValue 'string', 'shareProviderAuthority', 'git.neko.cryonix.scoped.controlfolder'
        resValue 'string', 'curseforge_api_key', 'DUMMY'
    }

    buildFeatures {
        buildConfig true
        prefab true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    sourceSets {
        main {
            java.srcDirs = [
                new File(pojavApp, 'src/main/java')
            ]
            res.srcDirs = [
                new File(pojavApp, 'src/main/res')
            ]
            assets.srcDirs = [
                new File(pojavApp, 'src/main/assets')
            ]
            jniLibs.srcDirs = [
                new File(pojavApp, 'src/main/jniLibs')
            ]
        }
    }

    ndkVersion = '25.2.9519653'

    externalNativeBuild {
        ndkBuild {
            path file('../engine/pojav/app_pojavlauncher/src/main/jni/Android.mk')
        }
    }

    packagingOptions {
        jniLibs {
            useLegacyPackaging = true
        }
        pickFirst '**/libbytehook.so'
        resources {
            excludes += [
                'META-INF/AL2.0',
                'META-INF/LGPL2.1'
            ]
        }
    }

    lint {
        abortOnError false
    }
}

afterEvaluate {
    tasks.matching { it.name == 'mergeDebugAssets' || it.name == 'mergeReleaseAssets' }.configureEach {
        dependsOn(
            ':pojav_forge_installer:jar',
            ':pojav_arc_dns_injector:jar',
            ':pojav_jre_lwjgl3glfw:jar'
        )
    }
}

dependencies {
    implementation 'javax.annotation:javax.annotation-api:1.3.2'
    implementation 'commons-codec:commons-codec:1.15'
    implementation 'androidx.preference:preference:1.2.0'
    implementation 'androidx.drawerlayout:drawerlayout:1.2.0'
    implementation 'androidx.viewpager2:viewpager2:1.1.0-beta01'
    implementation 'androidx.annotation:annotation:1.5.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.fragment:fragment:1.8.5'
    implementation 'com.google.android.material:material:1.12.0'

    implementation 'com.github.duanhong169:checkerboarddrawable:1.0.2'
    implementation 'com.github.PojavLauncherTeam:portrait-sdp:ed33e89cbc'
    implementation 'com.github.PojavLauncherTeam:portrait-ssp:6c02fd739b'
    implementation 'com.github.Mathias-Boulay:ExtendedView:1.0.0'
    implementation 'com.github.Mathias-Boulay:android_gamepad_remapper:2.0.3'
    implementation 'com.github.Mathias-Boulay:virtual-joystick-android:1.14'

    implementation 'org.tukaani:xz:1.8'
    implementation 'net.sourceforge.htmlcleaner:htmlcleaner:2.6.1'
    implementation 'com.bytedance:bytehook:1.0.9'
    implementation fileTree(dir: new File(pojavApp, 'libs'), include: ['*.jar', '*.aar'])
}
